format-version = 1

[descriptors.'cpython-3.10']
base-version = '3.10'
implementation = 'cpython'
providers = [ 'windows-embeddable', 'python-build', ]
title = 'Python 3.10'

[descriptors.'cpython-3.11']
base-version = '3.11'
implementation = 'cpython'
providers = [ 'windows-embeddable', 'python-build', ]
title = 'Python 3.11'

[descriptors.'cpython-3.12']
base-version = '3.12'
implementation = 'cpython'
providers = [ 'windows-embeddable', 'python-build', ]
title = 'Python 3.12'

#[descriptors.'cpython-3.13']
#base-version = '3.13'
#implementation = 'cpython'
#providers = [ 'windows-embeddable', 'python-build', ]
#title = 'Python 3.13'

# TODO: Enable after issues with no-binary installations with Pip have
#       been resolved.
#[descriptors.'cpython-3.10--tracerefs']
#base-version = '3.10'
#features = [ 'tracerefs', ]
#implementation = 'cpython'
#providers = [ 'python-build', ]
#title = 'Python 3.10 +TRACEREFS'

[descriptors.'pypy-3.10']
base-version = '3.10'
implementation = 'pypy'
providers = [ 'python-build', ]
title = 'PyPy 3.10'
