format-version = 1

[versions."cpython-3.7"]
base-version = "3.7"
implementation = "cpython"
implementation-version = "3.7.16"
providers = [
    "python-build",
]
title = "Python 3.7"

[versions."cpython-3.8"]
base-version = "3.8"
implementation = "cpython"
implementation-version = "3.8.16"
providers = [
    "python-build",
]
title = "Python 3.8"

[versions."cpython-3.9"]
base-version = "3.9"
implementation = "cpython"
implementation-version = "3.9.16"
providers = [
    "python-build",
]
title = "Python 3.9"

[versions."cpython-3.10"]
base-version = "3.10"
implementation = "cpython"
implementation-version = "3.10.9"
providers = [
    "python-build",
]
title = "Python 3.10"

[versions."cpython-3.11"]
base-version = "3.11"
implementation = "cpython"
implementation-version = "3.11.1"
providers = [
    "python-build",
]
title = "Python 3.11"

#[versions."cpython-3.8--tracerefs"]
#base-version = "3.8"
#features = [
#    "tracerefs",
#]
#implementation = "cpython"
#implementation-version = "3.8.16"
#providers = [
#    "python-build",
#]
#title = "Python 3.8 +TRACEREFS"

[versions."pypy-3.7"]
base-version = "3.7"
implementation = "pypy"
implementation-version = "7.3.9"
providers = [
    "python-build",
]
title = "PyPy 3.7"

[versions."pypy-3.8"]
base-version = "3.8"
implementation = "pypy"
implementation-version = "7.3.10"
providers = [
    "python-build",
]
title = "PyPy 3.8"

[versions."pypy-3.9"]
base-version = "3.9"
implementation = "pypy"
implementation-version = "7.3.10"
providers = [
    "python-build",
]
title = "PyPy 3.9"
