name: pr-tests
on:
  pull_request:
    branches: ['*']
jobs:
  initialize:
    uses: ./.github/workflows/reusable--initializer.yaml
  test-standard-suite:
    needs: initialize
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.initialize.outputs.python-versions-json) }}
    uses: ./.github/workflows/reusable--tester.yaml
    with:
      python-version: '${{ matrix.python-version }}'
