name: reusable--publisher
on:
  workflow_call:
    secrets:
      GHA_COMMIT_SIGNING_KEY:
        description: 'PGP/GPG private key with which to sign documentation commit.'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: emcd/python-devshim/.github/actions/python-venv@master
      - name: Load PGP Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: '${{ secrets.GHA_COMMIT_SIGNING_KEY }}'
      - name: Configure Git
        run: |
          git config user.name 'Github Actions Robot'
          git config user.email '${{ github.repository_owner }}@users.noreply.github.com'
      - name: Upload Github Pages
        run: /usr/bin/python3 develop.py publish.github-pages
        shell: bash
