name: reusable--publisher
on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: emcd/python-devshim/.github/actions/python-venv@master
      - name: Generate Documentation
        run: |
          set -eu -o pipefail
          /usr/bin/python3 develop.py make.html
          # TODO: Query artifacts location.
          touch .local/artifacts/html/sphinx/.nojekyll
        shell: bash
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .local/artifacts/html/sphinx
  publish:
    needs: generate
    permissions:
      id-token: write # to verify deployment originates from appropriate source
      pages: write    # to deploy to Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Pages Artifact
        id: deployment
        uses: actions/deploy-pages@v4
